from prism_vm_core.facade import (
    InternConfig,
    DEFAULT_INTERN_CONFIG,
    Cnf2Config,
    Cnf2Flags,
    DEFAULT_CNF2_CONFIG,
    DEFAULT_CNF2_FLAGS,
    CoordConfig,
    DEFAULT_COORD_CONFIG,
    _HAS_DEBUG_CALLBACK,
    _SCATTER_GUARD,
    _TEST_GUARDS,
    _GATHER_GUARD,
    _scatter_guard,
    _scatter_guard_strict,
    _key_order_commutative_host,
    _cnf2_enabled,
    _cnf2_slot1_enabled,
    _default_bsp_mode,
    _gpu_metrics_device_index,
    _gpu_metrics_enabled,
    _normalize_bsp_mode,
    _parse_milestone_value,
    _read_pytest_milestone,
    _servo_enabled,
    _scatter_drop,
    _scatter_strict,
    _pack_key,
    _lookup_node_id,
    _ledger_root_hash_host,
    _ledger_roots_hash_host,
    _candidate_indices,
    _scatter_compacted_ids,
    emit_candidates,
    compact_candidates,
    compact_candidates_with_index,
    intern_candidates,
    cycle,
    op_interact,
    cycle_intrinsic,
    RANK_COLD,
    RANK_FREE,
    RANK_HOT,
    RANK_WARM,
    _blocked_perm,
    op_morton,
    op_rank,
    op_sort_and_swizzle,
    op_sort_and_swizzle_blocked,
    op_sort_and_swizzle_blocked_with_perm,
    op_sort_and_swizzle_hierarchical,
    op_sort_and_swizzle_hierarchical_with_perm,
    op_sort_and_swizzle_morton,
    op_sort_and_swizzle_morton_with_perm,
    op_sort_and_swizzle_servo,
    op_sort_and_swizzle_servo_with_perm,
    op_sort_and_swizzle_with_perm,
    swizzle_2to1,
    swizzle_2to1_dev,
    swizzle_2to1_host,
    cd_lift_binary,
    coord_norm,
    coord_norm_batch,
    coord_xor,
    coord_xor_batch,
    apply_q,
    validate_stratum_no_future_refs,
    validate_stratum_no_future_refs_jax,
    validate_stratum_no_within_refs,
    validate_stratum_no_within_refs_jax,
    project_arena_to_ledger,
    project_manifest_to_ledger,
    dispatch_kernel,
    kernel_add,
    kernel_mul,
    optimize_ptr,
    coord_norm_probe_get,
    coord_norm_probe_reset,
    _damage_metrics_enabled,
    _damage_metrics_update,
    _damage_tile_size,
    damage_metrics_get,
    damage_metrics_reset,
    cnf2_metrics_get,
    cnf2_metrics_reset,
    GPUWatchdog,
    _gpu_watchdog_create,
    commit_stratum,
    cycle_candidates,
    init_arena,
    init_ledger,
    init_manifest,
    intern_nodes,
    ledger_has_corrupt,
    node_batch,
    safe_gather_1d,
)
from prism_vm_core.types import (
    LEDGER_CAPACITY,
    MAX_COORD_STEPS,
    MAX_COUNT,
    MAX_ID,
    MAX_KEY_NODES,
    MAX_ROWS,
    OP_ADD,
    OP_COORD_ONE,
    OP_COORD_PAIR,
    OP_COORD_ZERO,
    OP_MUL,
    OP_NAMES,
    OP_NULL,
    OP_SORT,
    OP_SUC,
    OP_ZERO,
    ArenaPtr,
    CommittedIds,
    HostBool,
    HostInt,
    LedgerId,
    ManifestPtr,
    ProvisionalIds,
    ZERO_PTR,
    Arena,
    CandidateBuffer,
    Ledger,
    Manifest,
    NodeBatch,
    StagingContext,
    Stratum,
    hyperstrata_precedes,
    staging_context_forgets_detail,
    QMap,
    _arena_ptr,
    _committed_ids,
    _host_bool,
    _host_bool_value,
    _host_int,
    _host_int_value,
    _host_raise_if_bad,
    _ledger_id,
    _manifest_ptr,
    _provisional_ids,
    _require_arena_ptr,
    _require_ledger_id,
    _require_manifest_ptr,
)
# NOTE: JAX op dtype normalization (int32) is assumed; tighten if drift appears
# (see IMPLEMENTATION_PLAN.md).


__all__ = [
    "OP_NULL",
    "OP_ZERO",
    "OP_SUC",
    "OP_ADD",
    "OP_MUL",
    "OP_SORT",
    "OP_COORD_ZERO",
    "OP_COORD_ONE",
    "OP_COORD_PAIR",
    "ZERO_PTR",
    "OP_NAMES",
    "ManifestPtr",
    "LedgerId",
    "ArenaPtr",
    "HostInt",
    "HostBool",
    "ProvisionalIds",
    "CommittedIds",
    "QMap",
    "MAX_ROWS",
    "MAX_KEY_NODES",
    "LEDGER_CAPACITY",
    "MAX_ID",
    "MAX_COUNT",
    "MAX_COORD_STEPS",
    "InternConfig",
    "DEFAULT_INTERN_CONFIG",
    "Cnf2Flags",
    "DEFAULT_CNF2_FLAGS",
    "Cnf2Config",
    "DEFAULT_CNF2_CONFIG",
    "CoordConfig",
    "DEFAULT_COORD_CONFIG",
    "safe_gather_1d",
    "coord_norm_probe_reset",
    "coord_norm_probe_get",
    "damage_metrics_reset",
    "cnf2_metrics_reset",
    "damage_metrics_get",
    "cnf2_metrics_get",
    "GPUWatchdog",
    "RANK_HOT",
    "RANK_WARM",
    "RANK_COLD",
    "RANK_FREE",
    "Manifest",
    "Arena",
    "Ledger",
    "CandidateBuffer",
    "NodeBatch",
    "_candidate_indices",
    "_pack_key",
    "_scatter_compacted_ids",
    "_lookup_node_id",
    "Stratum",
    "StagingContext",
    "hyperstrata_precedes",
    "staging_context_forgets_detail",
    "node_batch",
    "init_manifest",
    "init_arena",
    "init_ledger",
    "ledger_has_corrupt",
    "project_manifest_to_ledger",
    "project_arena_to_ledger",
    "_ledger_root_hash_host",
    "_ledger_roots_hash_host",
    "emit_candidates",
    "compact_candidates",
    "compact_candidates_with_index",
    "intern_candidates",
    "validate_stratum_no_within_refs_jax",
    "validate_stratum_no_within_refs",
    "validate_stratum_no_future_refs_jax",
    "validate_stratum_no_future_refs",
    "apply_q",
    "commit_stratum",
    "cycle_candidates",
    "op_rank",
    "coord_norm",
    "coord_xor",
    "cd_lift_binary",
    "coord_norm_batch",
    "coord_xor_batch",
    "intern_nodes",
    "op_sort_and_swizzle_with_perm",
    "op_sort_and_swizzle",
    "op_sort_and_swizzle_blocked_with_perm",
    "op_sort_and_swizzle_blocked",
    "_blocked_perm",
    "op_sort_and_swizzle_hierarchical_with_perm",
    "op_sort_and_swizzle_hierarchical",
    "swizzle_2to1_host",
    "swizzle_2to1_dev",
    "swizzle_2to1",
    "op_morton",
    "op_sort_and_swizzle_morton_with_perm",
    "op_sort_and_swizzle_morton",
    "op_sort_and_swizzle_servo_with_perm",
    "op_sort_and_swizzle_servo",
    "op_interact",
    "cycle_intrinsic",
    "cycle",
    "kernel_add",
    "kernel_mul",
    "optimize_ptr",
    "dispatch_kernel",
    "PrismVM",
    "PrismVM_BSP_Legacy",
    "PrismVM_BSP",
    "make_vm",
    "run_program_lines",
    "run_program_lines_arena",
    "run_program_lines_bsp",
    "repl",
]

# --- Host VM + CLI (drained to prism_cli.repl) ---
from prism_cli.repl import (
    PrismVM,
    PrismVM_BSP,
    PrismVM_BSP_Legacy,
    make_vm,
    repl,
    run_program_lines,
    run_program_lines_arena,
    run_program_lines_bsp,
    main,
)

# --- Dependency-injected facade re-exports (drain prism_vm) ---
from prism_bsp.arena_step import cycle as _cycle_di, op_interact as _op_interact_di
from prism_bsp.intrinsic import cycle_intrinsic as _cycle_intrinsic_di
from prism_bsp.space import op_rank as _op_rank_di
from prism_coord.coord import (
    cd_lift_binary as _cd_lift_binary_di,
    coord_norm as _coord_norm_di,
    coord_norm_batch as _coord_norm_batch_di,
    coord_xor as _coord_xor_di,
    coord_xor_batch as _coord_xor_batch_di,
)
from prism_semantics.commit import (
    apply_q as _apply_q_di,
    validate_stratum_no_future_refs as _validate_stratum_no_future_refs_di,
    validate_stratum_no_within_refs as _validate_stratum_no_within_refs_di,
)
from prism_semantics.project import (
    project_arena_to_ledger as _project_arena_to_ledger_di,
    project_manifest_to_ledger as _project_manifest_to_ledger_di,
)

cycle_intrinsic = _cycle_intrinsic_di
cycle = _cycle_di
op_interact = _op_interact_di
op_rank = _op_rank_di
coord_norm = _coord_norm_di
coord_xor = _coord_xor_di
coord_norm_batch = _coord_norm_batch_di
coord_xor_batch = _coord_xor_batch_di
cd_lift_binary = _cd_lift_binary_di
apply_q = _apply_q_di
validate_stratum_no_within_refs = _validate_stratum_no_within_refs_di
validate_stratum_no_future_refs = _validate_stratum_no_future_refs_di
project_manifest_to_ledger = _project_manifest_to_ledger_di
project_arena_to_ledger = _project_arena_to_ledger_di


if __name__ == "__main__":
    main()
