"""Type-surface re-exports for Prism VM.

This module centralizes structural/constant exports separate from the
facade control surface, improving auditability and import hygiene.
"""

from prism_vm_core.constants import (
    LEDGER_CAPACITY,
    MAX_COORD_STEPS,
    MAX_COUNT,
    MAX_ID,
    MAX_KEY_NODES,
    MAX_ROWS,
)
from prism_vm_core.ontology import (
    OP_ADD,
    OP_COORD_ONE,
    OP_COORD_PAIR,
    OP_COORD_ZERO,
    OP_MUL,
    OP_NAMES,
    OP_NULL,
    OP_SORT,
    OP_SUC,
    OP_ZERO,
    ArenaPtr,
    CommittedIds,
    HostBool,
    HostInt,
    LedgerId,
    ManifestPtr,
    ProvisionalIds,
    ZERO_PTR,
)
from prism_vm_core.structures import (
    Arena,
    CandidateBuffer,
    Ledger,
    Manifest,
    NodeBatch,
    StagingContext,
    Stratum,
    hyperstrata_precedes,
    staging_context_forgets_detail,
)
from prism_core.compact import (
    CompactResult,
    CompactConfig,
    DEFAULT_COMPACT_CONFIG,
)
from prism_core.alloc import AllocConfig, DEFAULT_ALLOC_CONFIG
from prism_vm_core.domains import (
    QMap,
    _arena_ptr,
    _committed_ids,
    _host_bool,
    _host_bool_value,
    _host_int,
    _host_int_value,
    _host_raise_if_bad,
    _ledger_id,
    _manifest_ptr,
    _provisional_ids,
    _require_arena_ptr,
    _require_ledger_id,
    _require_manifest_ptr,
)

__all__ = [
    "LEDGER_CAPACITY",
    "MAX_COORD_STEPS",
    "MAX_COUNT",
    "MAX_ID",
    "MAX_KEY_NODES",
    "MAX_ROWS",
    "OP_ADD",
    "OP_COORD_ONE",
    "OP_COORD_PAIR",
    "OP_COORD_ZERO",
    "OP_MUL",
    "OP_NAMES",
    "OP_NULL",
    "OP_SORT",
    "OP_SUC",
    "OP_ZERO",
    "ArenaPtr",
    "CommittedIds",
    "HostBool",
    "HostInt",
    "LedgerId",
    "ManifestPtr",
    "ProvisionalIds",
    "ZERO_PTR",
    "Arena",
    "CandidateBuffer",
    "CompactResult",
    "CompactConfig",
    "DEFAULT_COMPACT_CONFIG",
    "AllocConfig",
    "DEFAULT_ALLOC_CONFIG",
    "Ledger",
    "Manifest",
    "NodeBatch",
    "StagingContext",
    "Stratum",
    "hyperstrata_precedes",
    "staging_context_forgets_detail",
    "QMap",
    "_arena_ptr",
    "_committed_ids",
    "_host_bool",
    "_host_bool_value",
    "_host_int",
    "_host_int_value",
    "_host_raise_if_bad",
    "_ledger_id",
    "_manifest_ptr",
    "_provisional_ids",
    "_require_arena_ptr",
    "_require_ledger_id",
    "_require_manifest_ptr",
]
